// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFCJmROB-vrMRzM2MINix8ax3VJebp-FQ',
    appId: '1:474658779481:web:5f44a862c4db8384bf9c48',
    messagingSenderId: '474658779481',
    projectId: 'al-burhaan-389412',
    authDomain: 'al-burhaan-389412.firebaseapp.com',
    storageBucket: 'al-burhaan-389412.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWMoGQ4qnVo23UXjXr4ipV90Cj_2t3kn4',
    appId: '1:474658779481:android:bfe7a7eb73d6b56dbf9c48',
    messagingSenderId: '474658779481',
    projectId: 'al-burhaan-389412',
    storageBucket: 'al-burhaan-389412.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFKgDWtGF43QJ6moW-vd3hf9_ETbpWiUQ',
    appId: '1:474658779481:ios:a45118b5b2707e5bbf9c48',
    messagingSenderId: '474658779481',
    projectId: 'al-burhaan-389412',
    storageBucket: 'al-burhaan-389412.appspot.com',
    androidClientId: '474658779481-75lv9fsrokff7opu8jrevc7kpend64uj.apps.googleusercontent.com',
    iosClientId: '474658779481-kcslcckl4kuj09qc7ldvjlml66ll98di.apps.googleusercontent.com',
    iosBundleId: 'al.burhaan.alburhaan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFKgDWtGF43QJ6moW-vd3hf9_ETbpWiUQ',
    appId: '1:474658779481:ios:a45118b5b2707e5bbf9c48',
    messagingSenderId: '474658779481',
    projectId: 'al-burhaan-389412',
    storageBucket: 'al-burhaan-389412.appspot.com',
    androidClientId: '474658779481-75lv9fsrokff7opu8jrevc7kpend64uj.apps.googleusercontent.com',
    iosClientId: '474658779481-kcslcckl4kuj09qc7ldvjlml66ll98di.apps.googleusercontent.com',
    iosBundleId: 'al.burhaan.alburhaan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFCJmROB-vrMRzM2MINix8ax3VJebp-FQ',
    appId: '1:474658779481:web:2df6f8852e76d7f2bf9c48',
    messagingSenderId: '474658779481',
    projectId: 'al-burhaan-389412',
    authDomain: 'al-burhaan-389412.firebaseapp.com',
    storageBucket: 'al-burhaan-389412.appspot.com',
  );
}
