// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBHiTBZIcxNeqwe89td-iUGhNVbBi2ytbQ',
//     appId: '1:499974864793:web:0e1e3e5c8778deec1d1d08',
//     messagingSenderId: '499974864793',
//     projectId: 'al-burhaan-cec08',
//     authDomain: 'al-burhaan-cec08.firebaseapp.com',
//     storageBucket: 'al-burhaan-cec08.appspot.com',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD8dbOsl0kHkHmnxv7-M3EAmZ_LZIwWzOc',
//     appId: '1:499974864793:android:a772fb0961d9cbaa1d1d08',
//     messagingSenderId: '499974864793',
//     projectId: 'al-burhaan-cec08',
//     storageBucket: 'al-burhaan-cec08.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAU2wPHYvZUqUlwvEybjCanZil1IT_jT_w',
//     appId: '1:499974864793:ios:d2631116fd3440051d1d08',
//     messagingSenderId: '499974864793',
//     projectId: 'al-burhaan-cec08',
//     storageBucket: 'al-burhaan-cec08.appspot.com',
//     iosBundleId: 'al.burhaan.alburhaan',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAU2wPHYvZUqUlwvEybjCanZil1IT_jT_w',
//     appId: '1:499974864793:ios:d2631116fd3440051d1d08',
//     messagingSenderId: '499974864793',
//     projectId: 'al-burhaan-cec08',
//     storageBucket: 'al-burhaan-cec08.appspot.com',
//     iosBundleId: 'al.burhaan.alburhaan',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBHiTBZIcxNeqwe89td-iUGhNVbBi2ytbQ',
//     appId: '1:499974864793:web:b74def8fce4c95201d1d08',
//     messagingSenderId: '499974864793',
//     projectId: 'al-burhaan-cec08',
//     authDomain: 'al-burhaan-cec08.firebaseapp.com',
//     storageBucket: 'al-burhaan-cec08.appspot.com',
//   );
// }
