// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwoH8a8YfwatXJrTYusma2_EpkYqa1YZI',
    appId: '1:28089316114:web:73a7898209d5736a85b9cb',
    messagingSenderId: '28089316114',
    projectId: 'al-burhaan-app',
    authDomain: 'al-burhaan-app.firebaseapp.com',
    storageBucket: 'al-burhaan-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn30RrlLfacwnZw5RFfntlH-4u9Ligzo4',
    appId: '1:28089316114:android:a3a6dfb99a9343ff85b9cb',
    messagingSenderId: '28089316114',
    projectId: 'al-burhaan-app',
    storageBucket: 'al-burhaan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBynr8U657KQl6B25qTxIkBwCbWDJ5Rd94',
    appId: '1:28089316114:ios:91030410040b79a285b9cb',
    messagingSenderId: '28089316114',
    projectId: 'al-burhaan-app',
    storageBucket: 'al-burhaan-app.firebasestorage.app',
    iosBundleId: 'com.example.burhaanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBynr8U657KQl6B25qTxIkBwCbWDJ5Rd94',
    appId: '1:28089316114:ios:91030410040b79a285b9cb',
    messagingSenderId: '28089316114',
    projectId: 'al-burhaan-app',
    storageBucket: 'al-burhaan-app.firebasestorage.app',
    iosBundleId: 'com.example.burhaanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwoH8a8YfwatXJrTYusma2_EpkYqa1YZI',
    appId: '1:28089316114:web:bb097a35e054b35485b9cb',
    messagingSenderId: '28089316114',
    projectId: 'al-burhaan-app',
    authDomain: 'al-burhaan-app.firebaseapp.com',
    storageBucket: 'al-burhaan-app.firebasestorage.app',
  );
}
